### ISSUE TITLE
Issues Running on Mac OS X 10. 

### ISSUE THREAD

**Issue by mfa89** [zach-morris/plugin.program.iarl#30] opened 2017-04-19 01:33 UTC
Hello, 

I have combed over your instructions to a T. I have even browsed other routes to get this all set up, but all of them have left me short. I have reinstalled all of it numerous times to see if I missed some random step but that is not the case. As of now, here are the issues I have had.

1. On RetroArch, I go through all the steps in your tutorial, then when I go to IARL in Kodi I continue to follow the steps and when I try and open a game I get all the way through the download/launch when a small icon pops up and disappears in the blink of an eye before taking me back to the main game screen. I tried to reconfigured numerous different variables to see if I was missing something and nothing has worked. 

2. I then decided to see if I could run them in the RetroArch interface, and with no luck there either. When I load the core and then try to download the content, there is nothing there. Even though I have gone through all my files to ensure that I have them going to the right place, and then re downloaded and re updated all of the categories. 

Am I missing something so obvious? Any insight would be greatly appreciated, There are not too many users (from what I have seen) using a Mac for this. 

Thanks.

**Comment by zach-morris** [comment] 2017-04-19 03:29
The popping up and then disappearing is a sign that a command was sent, but Retroarch didn't like the command for whatever reason.  Can you provide a kodi [debug log](http://kodi.wiki/view/Log_file/Easy)?

**Comment by mfa89** [comment] 2017-04-19 20:47
http://paste.ubuntu.com/24415972

I believe I followed all the steps for the debug, If it doesn't work for you, let me know and I will try again. Thanks!!

**Comment by zach-morris** [comment] 2017-04-19 22:00
So, like you said it looks like you have it setup correctly in the addon.  The problem lies with Retroarch.
The command to launch the game is sent is per this log line:
``IARL:  External launch command sent: "/Volumes/RetroArch/RetroArch.app/Contents/MacOS/RetroArch"  -L "/Volumes/RetroArch/RetroArch.app/Contents/Resources/cores/mupen64plus_libretro.dylib" "/Users/Michael/Library/Application Support/Kodi/userdata/addon_data/plugin.program.iarl/temp_iarl/007 - GoldenEye (USA).n64"``

I tried this game on my mac and it works with the mupen64plus_libretro core.  Suggestions to troubleshoot:
1)  Open up Retroarch and ensure you have updated the core to the latest mupen64plus_libretro, and try again
2)  In IARL, select Download only.  Then in Retroarch, navigate to this folder from the 'Load Content' selection and try to launch the file:
``/Users/Michael/Library/Application Support/Kodi/userdata/addon_data/plugin.program.iarl/temp_iarl/``
3)  Paste the command from the log into the Mac Terminal Command Prompt and add "--verbose" to the end to see why Retroarch isn't happy.  The command would be:
``"/Volumes/RetroArch/RetroArch.app/Contents/MacOS/RetroArch"  -L "/Volumes/RetroArch/RetroArch.app/Contents/Resources/cores/mupen64plus_libretro.dylib" "/Users/Michael/Library/Application Support/Kodi/userdata/addon_data/plugin.program.iarl/temp_iarl/007 - GoldenEye (USA).n64" --verbose``

**Comment by mfa89** [comment] 2017-04-19 22:56
Michaels-MacBook-Pro-2:~ Michael$
"/Volumes/RetroArch/RetroArch.app/Contents/MacOS/RetroArch" -L
"/Volumes/RetroArch/RetroArch.app/Contents/Resources/cores/mupen64plus_libretro.dylib"
"/Users/Michael/Library/Application
Support/Kodi/userdata/addon_data/plugin.program.iarl/temp_iarl/007 -
GoldenEye (USA).n64" --verbose

RetroArch [INFO] :: Redirecting save file to
"/Users/Michael/Library/Application
Support/Kodi/userdata/addon_data/plugin.program.iarl/temp_iarl/007 -
GoldenEye (USA).srm".

RetroArch [INFO] :: === Build =======================================

Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AVX2 AES

Built: Mar 13 2017

RetroArch [INFO] :: Version: 1.5.0

RetroArch [INFO] :: =================================================

RetroArch [INFO] :: Loading default config.

RetroArch [ERROR] :: RetroArch is built for dynamic libretro cores, but
libretro_path is not set. Cannot continue.

RetroArch [ERROR] :: Fatal error received in: "init_libretro_sym()"

RetroArch [ERROR] :: This core requires a content file.



that was the command prompt for the issue, I was able to find the temp
download in the Retroarch program and use that, if worst comes to worst I
can keep downloading through your add on and just play on retroarch, I
would just prefer to use kodi, since I use that for my everyday lifestyle.

**Comment by zach-morris** [comment] 2017-04-19 23:21
I can recreate your error if the core is not found.  I will also note now that I'm looking a little closer, it looks like you have the Retroarch application located in a weird spot.  Looks like you have it on a separate USB storage device or something?  It shouldn't matter...  But for comparison, I have the Retroarch application in my 'Applications' folder on the main hard drive, and the command IARL sends for my setup is:
``"/Applications/RetroArch.app/Contents/MacOS/RetroArch"  -L "/Applications/RetroArch.app/Contents/Resources/cores/mupen64plus_libretro.dylib" "/Users/ZC/Library/Application Support/Kodi/userdata/addon_data/plugin.program.iarl/temp_iarl/007 - GoldenEye (USA).n64"``

Anyway, one of the two things is wrong.  Either:
1)  You did not go and update/download the core in Retroarch.
You can check this:  On your mac, right click on the Retroarch app and select show app contents, then go to:
Contents/Resources/cores
and ensure the file is in the folder
mupen64plus_libretro.dylib

The full path to that file should be:
``/Volumes/RetroArch/RetroArch.app/Contents/Resources/cores/mupen64plus_libretro.dylib``

or

2)  Retroarch is downloading the core to some other non-standard location.
You can check this:  Start Retroarch, go to the settings section, then select Directories near the bottom.  The core directory setting should be:
``/Volumes/RetroArch/RetroArch.app/Contents/Resources/cores/``

If its number 1, then download the core in Retroarch and make sure the file shows up in that folder.  If its number 2, then you can either change it back to the default, or put in a non-standard command per [these instructions](https://github.com/zach-morris/plugin.program.iarl/wiki/5.--FAQ#3--i-want-to-use-emulator-xxx-instead).  Really, all that IARL is doing is automating the commands you would otherwise paste into the terminal.

**Comment by mfa89** [comment] 2017-04-19 23:41
For step number 1, when I click on the resources tab there is no option for Cores. Im assuming this is my problem. Any thought on correcting it?

**Comment by zach-morris** [comment] 2017-04-20 02:02
If there is no cores folder in
``/Volumes/RetroArch/RetroArch.app/Contents/Resources/``
and you were in Retroarch and selected update core and downloaded at least one core, then Retroarch is probably putting them in some non-standard place (number 2).
You can check this: Start Retroarch, go to the settings section, then select Directories near the bottom. The core directory will probably not be the default setting:
/Volumes/RetroArch/RetroArch.app/Contents/Resources/cores/

**Comment by mfa89** [comment] 2017-04-20 15:32
I am still unable to get it to work, and currently, as of this morning the new problem is I can not find any temp downloads from when I download through kodi and try to open up in retroarch. None of the settings changed, they just are now downloading to a new folder that I can not find. I honestly feel like I am missing something so simple and I'm going to smack myself when it finally works right. 

I did go through retro arch and look to see where the core folder is and it's not there, I changed the default download back to what it should be, but when I go to download the content there is nothing there. 

Sent from my iPhone

Michael Allen

**Comment by mfa89** [comment] 2017-04-20 15:51
I ran another debug, the code for that is 

http://paste.unbuntu.com/24420829 <http://paste.unbuntu.com/24420829> 

I tried to download a different game, according to the key log (assuming I’m reading it right) it says that it is downloading the file to that temp file under the iarl plug in location. But when I go to Retroarch there is nothing there.

**Comment by mfa89** [comment] 2017-04-20 16:08
I apologize for the numerous emails, just letting you know issues as I go. 

I tried downloading another game, the only successful games I have been able to get to work on Retroarch are the james bond game and Zelda Ocarina of time. They are currently saved under the ‘history’ tab on retroarch, however in order for me to play them I need to go download them again in kodi (which isn’t an issue) but when I try to download a different game then it doesn’t show up at all in the temp folder the way those 2 games did. 

I really appreciate your patience and customer service on this. You’ve been a great help so far. 

Thanks.

**Comment by zach-morris** [comment] 2017-04-21 03:21
By default, the files are downloaded to a [temp directory](https://github.com/zach-morris/plugin.program.iarl/wiki/5.--FAQ#2-where-are-the-games-downloaded-to).
``/Users/Michael/Library/Application Support/Kodi/userdata/addon_data/plugin.program.iarl/temp_iarl/``
There is a setting in the IARL for download cache, which is by default 0, meaning it will only download and store the files required to play the selected game.  You can either raise the cache to something higher via the [settings](https://github.com/zach-morris/plugin.program.iarl/wiki/2.--Addon-Settings#iarl-addon-settings) or change the folder to [wherever you want the files to go](https://github.com/zach-morris/plugin.program.iarl/wiki/2.--Addon-Settings#game-archive-xml-settings) and keep them indefinitely.

Take a look at the [addon settings](https://github.com/zach-morris/plugin.program.iarl/wiki/2.--Addon-Settings), and the [FAQ](https://github.com/zach-morris/plugin.program.iarl/wiki/5.--FAQ).
IARL should work assuming you've followed the instructions for basic playing of games, but you can tweak the settings to make it work for your setup.  Whenever you figure out what ultimately the issue is with your setup, let me know so I can update the wiki.

**Comment by mfa89** [comment] 2017-04-21 15:13
Updating the cache worked great! Thanks! Last and final issue, I am only able to play the N64 games. When I try to use the Playstation Archive it originally asked for my user name and login for archive, when I inputted that and tried again, I clicked download and it downloaded for a split second and then the download screen went away. Thoughts?

**Comment by zach-morris** [comment] 2017-04-21 17:49
Probably wrong credentials.  From the wiki:
Also note. Your login credentials are you archive.org user EMAIL and password.

Sounds like you got it working/launching with IARL?  Any suggestions on wiki updates let me know.

**Comment by mfa89** [comment] 2017-04-21 18:02
I have it working using retroarch, so downloading from IARL into retroarch, then finding the temp file and playing from there. I have yet to figure out why it's not working when I try to launch from kodi. Would a debug log show why this is happening? 

As for the credentials, I have tried them numerous times, my info is correct. It no longer tells me to log in. It just starts the download and then automatically disappears. 

As for updates to the wiki, it is pretty straight forward. I would consider adding in a sections for troubleshooting the way I have. I.E. displaying scenarios to find the temp file in case it's not launching from the IARL add on. 


Michael

**Comment by zach-morris** [comment] 2017-04-21 18:26
OK, I'll close this issue with those suggestions.

**Closed by zach-morris** 2017-04-21 18:26 UTC

**Comment by mfa89** [comment] 2017-04-21 19:04
Can you look at this debug log for me? Its showing some weird txt when i try to download a PS1 game. 

paste.ubuntu.com/24428549 <http://paste.ubuntu.com/24428549>
